### ISSUE TITLE
FB Warns reported for Freeman

### ISSUE THREAD

**Issue by vv-monsalve** [rfuenzalida/Freeman#11]
The following are the warns reported by Fontbakery 

<details><summary>⚠ <b>WARN:</b> Checking OS/2 achVendID. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id">com.google.fonts/check/vendor_id</a>)</summary><div>

>
>Microsoft keeps a list of font vendors and their respective contact info. This list is updated regularly and is indexed by a 4-char "Vendor ID" which is stored in the achVendID field of the OS/2 table.
>
>Registering your ID is not mandatory, but it is a good practice since some applications may display the type designer / type foundry contact info on some dialog and also because that info will be visible on Microsoft's website:
>
>https://docs.microsoft.com/en-us/typography/vendors/
>
>This check verifies whether or not a given font's vendor ID is registered in that list or if it has some of the default values used by the most common font editors.
>
>Each new FontBakery release includes a cached copy of that list of vendor IDs. If you registered recently, you're safe to ignore warnings emitted by this check, since your ID will soon be included in one of our upcoming releases.
>
* ⚠ **WARN** OS/2 VendorID value 'NEWT' is not yet recognized. If you registered it recently, then it's safe to ignore this warning message. Otherwise, you should set it to your own unique 4 character code, and register it with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx
 [code: unknown]
</div></details><details><summary>⚠ <b>WARN:</b> Check Google Fonts glyph coverage. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage">com.google.fonts/check/glyph_coverage</a>)</summary><div>

>
>Google Fonts expects that fonts in its collection support at least the minimal set of characters defined in the `GF-latin-core` glyph-set.
>
* ⚠ **WARN** GF_Latin_Plus is almost fulfilled. Missing codepoints:

	- 0x20B4 (HRYVNIA SIGN)

	- 0x20B8 (TENGE SIGN)

	- 0x20AE (TUGRIK SIGN)

	- 0x2016 (DOUBLE VERTICAL LINE)

	- 0x0E3F (THAI CURRENCY SYMBOL BAHT)

	- 0x20BF (BITCOIN SIGN)

	- 0x20BE (LARI SIGN)

	- 0x20A8 (RUPEE SIGN)

	- 0x20AA (NEW SHEQEL SIGN)

	- 0x2197 (NORTH EAST ARROW)

	- 0x2198 (SOUTH EAST ARROW)

	- 0x2199 (SOUTH WEST ARROW)

	- 0x2196 (NORTH WEST ARROW)

	- 0x2194 (LEFT RIGHT ARROW)

	- 0x2195 (UP DOWN ARROW)

	- 0x25CF (BLACK CIRCLE)

	- 0x25CB (WHITE CIRCLE)

	- 0x25E6 (WHITE BULLET)

	- 0x25AA (BLACK SMALL SQUARE)

	- 0x25AB (WHITE SMALL SQUARE)

	- 0x25B4 (BLACK UP-POINTING SMALL TRIANGLE)

	- 0x25B8 (BLACK RIGHT-POINTING SMALL TRIANGLE)

	- 0x25BE (BLACK DOWN-POINTING SMALL TRIANGLE)

	- 0x25C2 (BLACK LEFT-POINTING SMALL TRIANGLE)

	- 0x25B5 (WHITE UP-POINTING SMALL TRIANGLE)

	- 0x25B9 (WHITE RIGHT-POINTING SMALL TRIANGLE)

	- 0x25BF (WHITE DOWN-POINTING SMALL TRIANGLE)
 

	- And 0x25C3 (WHITE LEFT-POINTING SMALL TRIANGLE)
 [code: missing-codepoints]
* ⚠ **WARN** GF_TransLatin_Pinyin is almost fulfilled. Missing codepoints:

	- 0x207F (SUPERSCRIPT LATIN SMALL LETTER N)
 

	- And 0x1D3A (MODIFIER LETTER CAPITAL N)
 [code: missing-codepoints]
* ⚠ **WARN** GF_Latin_African is almost fulfilled. Missing codepoints:

	- 0x1D7E (LATIN SMALL CAPITAL LETTER U WITH STROKE)

	- 0x207F (SUPERSCRIPT LATIN SMALL LETTER N)

	- 0x1D58 (MODIFIER LETTER SMALL U)
 

	- And 0x1D5B (MODIFIER LETTER SMALL V)
 [code: missing-codepoints]
* ⚠ **WARN** GF_TransLatin_Arabic is almost fulfilled. Missing codepoints:

	- 0x1E96 (LATIN SMALL LETTER H WITH LINE BELOW)
 

	- And 0x02BD (MODIFIER LETTER REVERSED COMMA)
 [code: missing-codepoints]
</div></details><details><summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets">com.google.fonts/check/ligature_carets</a>)</summary><div>

>
>All ligatures in a font must have corresponding caret (text cursor) positions defined in the GDEF table, otherwhise, users may experience issues with caret rendering.
>
>If using GlyphsApp or UFOs, ligature carets can be defined as anchors with names starting with 'caret_'. These can be compiled with fontmake as of version v2.4.0.
>
* ⚠ **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]
</div></details><details><summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences">com.google.fonts/check/kerning_for_non_ligated_sequences</a>)</summary><div>

>
>Fonts with ligatures should have kerning on the corresponding non-ligated sequences for text where ligatures aren't used (eg https://github.com/impallari/Raleway/issues/14).
>
* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:

	- f + f

	- f + i

	- i + f

	- f + l

	- l + f 

	- And i + l [code: lacks-kern-info]
</div></details><details><summary>⚠ <b>WARN:</b> Check font contains no unreachable glyphs (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/unreachable_glyphs">com.google.fonts/check/unreachable_glyphs</a>)</summary><div>

>
>Glyphs are either accessible directly through Unicode codepoints or through substitution rules.
>
>In Color Fonts, glyphs are also referenced by the COLR table.
>
>Any glyphs not accessible by either of these means are redundant and serve only to increase the font's file size.
>
* ⚠ **WARN** The following glyphs could not be reached by codepoint or substitution rules:

	- B.ori

	- C.ori

	- E.ori

	- F.ori

	- G.ori

	- Hbar.ori

	- IJ.ori

	- IJacute

	- K.ori

	- M.ori

	- O.ori

	- P.ori

	- R.ori

	- S.ori

	- Thorn.ori

	- U1D453

	- V.ori

	- W.ori

	- ampersand.002

	- at.ori

	- barcomp

	- eight.sinf

	- eight.subs

	- eight.sups

	- five.sinf

	- five.subs

	- five.sups

	- four.sinf

	- four.subs

	- four.sups

	- g.001

	- germandbls.001

	- ijacute

	- llinebelowcomb

	- macronbelow

	- nine.sinf

	- nine.subs

	- nine.sups

	- one.sinf

	- one.subs

	- one.sups

	- section.001

	- seven.sinf

	- seven.subs

	- seven.sups

	- six.sinf

	- six.subs

	- six.sups

	- sterling.001

	- sterling.002

	- sterling.003

	- sterling.004

	- three.sinf

	- three.subs

	- three.sups

	- two.sinf

	- two.subs

	- two.sups

	- uni0268.dotless

	- uni0336.case

	- zero.sinf

	- zero.subs 

	- And zero.sups
 [code: unreachable-glyphs]
</div></details><details><summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/contour_count">com.google.fonts/check/contour_count</a>)</summary><div>

>
>Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be constructured in a handful of ways. This means a glyph's contour count will only differ slightly amongst different fonts, e.g a 'g' could either be 2 or 3 contours, depending on whether its double story or single story.
>
>However, a quotedbl should have 2 contours, unless the font belongs to a display family.
>
>This check currently does not cover variable fonts because there's plenty of alternative ways of constructing glyphs with multiple outlines for each feature in a VarFont. The expected contour count data for this check is currently optimized for the typical construction of glyphs in static fonts.
>
* ⚠ **WARN** This font has a 'Soft Hyphen' character (codepoint 0x00AD) which is supposed to be zero-width and invisible, and is used to mark a hyphenation possibility within a word in the absence of or overriding dictionary hyphenation. It is mostly an obsolete mechanism now, and the character is only included in fonts for legacy codepage coverage. [code: softhyphen]
* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

	- Glyph name: aogonek	Contours detected: 3	Expected: 2

	- Glyph name: dcroat	Contours detected: 3	Expected: 2

	- Glyph name: eogonek	Contours detected: 3	Expected: 2

	- Glyph name: Uogonek	Contours detected: 2	Expected: 1

	- Glyph name: uogonek	Contours detected: 2	Expected: 1

	- Glyph name: uni01B6	Contours detected: 2	Expected: 1

	- Glyph name: uni01E5	Contours detected: 3	Expected: 2

	- Glyph name: uni01EA	Contours detected: 3	Expected: 2

	- Glyph name: uni01EB	Contours detected: 3	Expected: 2

	- Glyph name: uni01EC	Contours detected: 4	Expected: 3

	- Glyph name: uni01ED	Contours detected: 4	Expected: 3

	- Glyph name: uni01F5	Contours detected: 4	Expected: 3

	- Glyph name: uni0228	Contours detected: 2	Expected: 1

	- Glyph name: uni0229	Contours detected: 3	Expected: 2

	- Glyph name: uni023A	Contours detected: 2	Expected: 3

	- Glyph name: uni023D	Contours detected: 2	Expected: 1

	- Glyph name: uni023E	Contours detected: 1	Expected: 2

	- Glyph name: uni0247	Contours detected: 2	Expected: 4

	- Glyph name: uni1E08	Contours detected: 3	Expected: 2

	- Glyph name: uni1E09	Contours detected: 3	Expected: 2

	- Glyph name: uni1E1C	Contours detected: 3	Expected: 2

	- Glyph name: uni1E1D	Contours detected: 4	Expected: 3

	- Glyph name: uni20A6	Contours detected: 4	Expected: 1, 3 or 5

	- Glyph name: Uogonek	Contours detected: 2	Expected: 1

	- Glyph name: aogonek	Contours detected: 3	Expected: 2

	- Glyph name: dcroat	Contours detected: 3	Expected: 2

	- Glyph name: eogonek	Contours detected: 3	Expected: 2

	- Glyph name: fi	Contours detected: 2	Expected: 3

	- Glyph name: fl	Contours detected: 1	Expected: 2

	- Glyph name: uni01B6	Contours detected: 2	Expected: 1

	- Glyph name: uni01E5	Contours detected: 3	Expected: 2

	- Glyph name: uni01EC	Contours detected: 4	Expected: 3

	- Glyph name: uni01ED	Contours detected: 4	Expected: 3

	- Glyph name: uni0228	Contours detected: 2	Expected: 1

	- Glyph name: uni0229	Contours detected: 3	Expected: 2

	- Glyph name: uni023A	Contours detected: 2	Expected: 3

	- Glyph name: uni023D	Contours detected: 2	Expected: 1

	- Glyph name: uni023E	Contours detected: 1	Expected: 2

	- Glyph name: uni0247	Contours detected: 2	Expected: 4

	- Glyph name: uni1E08	Contours detected: 3	Expected: 2

	- Glyph name: uni1E09	Contours detected: 3	Expected: 2

	- Glyph name: uni1E1C	Contours detected: 3	Expected: 2

	- Glyph name: uni1E1D	Contours detected: 4	Expected: 3

	- Glyph name: uni20A6	Contours detected: 4	Expected: 1, 3 or 5 

	- And Glyph name: uogonek	Contours detected: 2	Expected: 1
 [code: contour-count]
</div></details>

**Comment by rfuenzalida** [comment]
All this WARN's have been revised.
