### ISSUE TITLE
Marks revision

### ISSUE THREAD

**Issue by vv-monsalve** [rfuenzalida/Freeman#18]
After doing the spacing and kerning adjustments, please give diacritic marks an overall revision.

- [x] Making all the marks balanced in width and weight. 
    - [x] Acute, grave, and tilde look a bit big and heavy
    - [x] Breve looks slightly lighter, especially when combined in stacked diacritics like `breve-acute`
    - [x] Revise `dcroat` stroke weight and position
    - [x] Create narrow marks to be combined with narrow letters such `I, i`
- [x] Adjust the sidebearings of letters horn glyphs
- [x] Add all the anchors to SSA base letters.

<img width="1830" alt="Screen Shot 2023-11-03 at 19 11 53" src="https://github.com/rfuenzalida/Freeman/assets/48698976/b5d469a6-3c24-4340-9db3-f9289719a32f">
<img width="1830" alt="Screen Shot 2023-11-03 at 19 19 23" src="https://github.com/rfuenzalida/Freeman/assets/48698976/0cb75d98-866a-4227-a3c8-93532ef9e54a">

**Comment by rfuenzalida** [comment]
This next commit has a revision of all the mark, won't close the issue until the new ones have been approved.

**Comment by vv-monsalve** [comment]
@rfuenzalida 

The stacked diacritics use rotated components which can cause rendering issues. Please find more details on our [Outline Quality Checklist](https://googlefonts.github.io/gf-guide/outlines.html#components).

You would like to create the Vietnamese combining marks with the stacked shapes adjusted for this purpose (in size, slope, distance, etc) and then use them for the composites.

<img width="710" alt="Screen Shot 2024-01-20 at 18 25 47" src="https://github.com/rfuenzalida/Freeman/assets/48698976/b0b8db5a-c991-4455-a847-5b69fd83e53e">
<img width="541" alt="Screen Shot 2024-01-20 at 18 26 02" src="https://github.com/rfuenzalida/Freeman/assets/48698976/3055c0de-0d04-4534-a50e-4ece69cc9e5a">

**Comment by rfuenzalida** [comment]
The next commit has this issue solved, stacked diacritics now have character created for them that works as composite.
