### ISSUE TITLE
Add the missing symbols

### ISSUE THREAD

**Issue by vv-monsalve** [rfuenzalida/Freeman#20]
<img width="1174" alt="Screen Shot 2023-11-03 at 19 47 18" src="https://github.com/rfuenzalida/Freeman/assets/48698976/7469c27e-4127-45fa-9a40-447aea2f01f9">

**Comment by rfuenzalida** [comment]
All this have been added, closing this issue.

**Comment by vv-monsalve** [comment]
Confirmed.
