### ISSUE TITLE
SSA marks and ccmp

### ISSUE THREAD

**Issue by vv-monsalve** [rfuenzalida/Freeman#24]
Please include 

- [x] The needed anchors to ensure the marks positioning for the SSA language support
- [x]  The ccmp rules needed to ensure the required replacements. You can check [Great-Vibes](https://github.com/googlefonts/great-vibes/tree/QA-GreatV) as a reference

You can locate the glyph sample shown in the picture below in the Output/CCMP folder on the [octo-text repository](https://github.com/SorkinType/octo-text/blob/main/Output/6%20CCMP/Google%20Fonts%20Africa%20SSA%20-%20CCMP%20test.txt). Additionally, the Output directory comprises a folder for [African Languages textures](https://github.com/SorkinType/octo-text/tree/main/Output/7%20African%20Language%20Textures), which correspond to those used in the #19 issue.

Please use both to test the font. You can use the proof files included in the .zip produced by the [`Build font and specimen` action](https://github.com/rfuenzalida/Freeman/actions/runs/6978403395) in the repo. Find it at the bottom of each run.

<img width="303" alt="Screen Shot 2023-11-24 at 10 52 20" src="https://github.com/rfuenzalida/Freeman/assets/48698976/002b64be-17b4-497b-a93e-21035d996733">

<img width="2167" alt="Screen Shot 2023-11-24 at 10 25 10" src="https://github.com/rfuenzalida/Freeman/assets/48698976/df04d3d7-2873-4741-b456-a7f48f9d63e3">

**Comment by rfuenzalida** [comment]
New source file should have all the CCMP and diacritics anchors needed to support SSA. 

![Screenshot 2023-11-28 at 15 57 33](https://github.com/rfuenzalida/Freeman/assets/8063083/0f12be3e-dd5d-451a-a32f-5ba48949c887)

**Comment by rfuenzalida** [comment]
Will wait for feedback before moving forward, thanks @vv-monsalve

**Comment by vv-monsalve** [comment]
After the latest revision performed with @EbenSorkin, we find the SSA support working (beyond the small fixes included in the latest PR). So closing this here.
