### ISSUE TITLE
DiffBrowsers results

### ISSUE THREAD

**Issue by vv-monsalve** [rfuenzalida/Freeman#3]
**Windows 10 chrome 71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/104540400-64b31480-55ed-11eb-8149-6559026f54c2.gif)

-----
**Windows 10 Edge 18**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/104540402-654bab00-55ed-11eb-80d9-3bda01c1d0e7.gif)

-----
**OS X High Sierra Safari 11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/104540393-61b82400-55ed-11eb-8869-d37e4afecaff.gif)

**Comment by vv-monsalve** [comment]
### Text Previews

**Windows 10 Chrome 71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/104540585-c07d9d80-55ed-11eb-805e-c488fbdf1f27.gif)

-----
**Windows 10 Edge 18**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/104540587-c1163400-55ed-11eb-9c6e-ef969ef795aa.gif)

------
**OS X High Sierra Safari 11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/104540582-bcea1680-55ed-11eb-8a87-e340dd8eba2a.gif)

**Comment by vv-monsalve** [comment]
New Text images after pulling the latest files in the repo at commit 9e56c3b6ac84df931afd2148f7296179a70e6857

-----
**Windows 10 Chrome 71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/106920626-4b2b5700-66d9-11eb-804e-abbc39089d61.gif)
-----
**Windows 10 Edge 18**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/106920632-4c5c8400-66d9-11eb-87cc-43e05cf5082c.gif)
-----
**OS X High Sierra Safari 11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/106920613-4797d000-66d9-11eb-85e4-3c88a8c0c388.gif)

**Comment by vv-monsalve** [comment]
New Waterfall preview images after pulling the latest files in the repo at commit 9e56c3b6ac84df931afd2148f7296179a70e6857

----
**Windows 10 Chrome 71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/106921705-41eeba00-66da-11eb-8bbf-5e9afa34dbb1.gif)

----
**Windows 10 Edge 18**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/106921708-42875080-66da-11eb-85e6-ab3f7911f208.gif)

----
**OS X High Sierra Safari 11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/106921693-3dc29c80-66da-11eb-8040-9ddd32a158f7.gif)

**Comment by rfuenzalida** [comment]
@vv-monsalve Thank you very much for this, let's wait to see what @davelab6 says about it.

**Comment by davelab6** [comment]
Sorry my delay responding to this, I'd like to hop on a video call to discuss

**Comment by vv-monsalve** [comment]
This issue corresponds to when these changes were considered an update to Françoise One. Given it is going to be published now as a new font, this comparison is no longer valid. Closing this issue here.
